### ISSUE TITLE
Error template helper should return error message, not the whole error object

### ISSUE THREAD

**Issue by vladbalan** [usefulio/forms#21]
Right now if you want to use the `{{error 'fieldName'}}` helper in your template it will display as `[object Object]`. The current method for showing the actual error message is:

```
{{#with error 'fieldName'}} 
  {{message}} 
{{/with}}
```

In my opinion this use case is the most frequent, so I propose we either:

a) Modify the output of the error helper from the `error` object to the `error.message` property 
_or_
b) Create a new `{{errorMessage 'fieldName'}}` helper

State your case on why we should do it one way or the other.

**Comment by cwohlman** [comment]
Let's go with option b.
