### ISSUE TITLE
[Feature Request] Hide/showing errors on keyup

### ISSUE THREAD

**Issue by delgermurun** [usefulio/forms#34]
After first time validation (submitting firs time), it is nice to show/hide errors re-actively while modifying field.

Just like autoform.

**Comment by cwohlman** [comment]
@delgermurun We'd like to keep the number of core features to a minimum, however you could easily implement this with just a few lines:

``` javascript
Forms.events({
  // Update the underlying document on keyup, instead of just
  // change
  'keyup input': function (e, tmpl) {
    var propertyName = e.currentTarget.name;
    if (propertyName && propertyName.length) {
      e.stopPropagation();
      e.stopImmediatePropagation();
      var changes = {};
      changes[propertyName] = e.currentTarget.type === "checkbox" ? e.currentTarget.checked : e.currentTarget.value;
      $(e.currentTarget).trigger('propertyChange', changes);
   }
  // validate the form on change
  // but only if there are outstanding errors, that way we don't validate an empty form
  // e.g. one that hasn't been submitted yet.
  'documentChange': function (e, tmpl) {
    if (tmpl.form.isInvalid())
      tmpl.form.validate();
  }
}
```

(I haven't tested the above code, so there might be bugs in my exact implementation.)

You could then submit a package with this code for others who want this kind of behavior on by default.

**Comment by delgermurun** [comment]
@cwohlman that makes sense. I really liked it's minimal approach. Thanks. I'll write package for it.
