### ISSUE TITLE
Confusion between `{{doc.propertyName}}` and `{{value "propertyName"}}`

### ISSUE THREAD

**Issue by ianserlin** [usefulio/forms#6]
In general I would prefer to get a magic `doc` variable available in my templates rather than using a special `{{value ..}}` helper.

This is because `{{doc.profile.firstName}}` more closely matches what I am used to and probably already have in a plain vanilla form than `{{value "profile.firstName}}`. Spacebars already handles deeply nested syntax for us.

So my question is, what is the additional value provided by the `{{value ...}}` syntax?

**Comment by cwohlman** [comment]
The reason I wrote it, and the only use case I can think of would be when
you want to reference the field name from a variable, e.g. `{{value
fieldName}}` where `fieldName` is in the current data context and is a
string containing the name of a field you want to access.

_Joshua Ohlman_
_Lead Developer_
_Useful IO_
_(361) 772-4201_
_joshua@useful.io_ joshua@useful.io

**Comment by ianserlin** [comment]
Ah, cool! Sounds like a powerful use-case. I suggest then to just use the `doc` syntax in the initial readme examples to make them more accessible, but keep the `{{value }}` helper as is. Thanks!

**Comment by cwohlman** [comment]
Great! Glad you like it :), I agree that it's better to use the `doc`
syntax in readme examples.

_Joshua Ohlman_
_Lead Developer_
_Useful IO_
_(361) 772-4201_
_joshua@useful.io_ joshua@useful.io

**Comment by gevou** [comment]
Noted
