### ISSUE TITLE
Form's data storage eliminates ability to use Collection Helpers?

### ISSUE THREAD

**Issue by ianserlin** [usefulio/forms#7]
More generally, collection helpers on a document just use the meteor `transform` functionality under the hood.

However, by storing an object as EJSON (which reactive-var/-dict do) does not store/restore methods (only properties), and so I believe any attached "helpers" won't be available to the developer writing the template (either in html or js).

Could this limitation be removed by storing the `doc` as a regular variable on the template instance and then using a `Tracker.dependency` instead of `ReactiveVar`? If so, that would be most excellent.

**Comment by cwohlman** [comment]
ReactiveVar stores objects by reference. One of it's greatest benefits, in
my opinions.

_Joshua Ohlman_
_Lead Developer_
_Useful IO_
_(361) 772-4201_
_joshua@useful.io_ joshua@useful.io

**Comment by ianserlin** [comment]
Boom, you're right. I didn't know that!
